name: progress_hud
description: A clean and lightweight progress HUD for your Flutter app
version: 0.0.1
author: Rafael Passos <r.passos@outlook.pt>
homepage: https://github.com/rcpassos/progress_hud

environment:
  sdk: ">=1.23.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0